spring:
  datasource:
    url: jdbc:mysql://localhost:3307/portalvagas?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true